### ISSUE TITLE
Unhandled Exception: MissingPluginException on MacOS

### ISSUE THREAD

**Issue by Zfinix** [rodydavis/flutter_midi#15]
I added the plugin and decided to follow the example, but i get this error:

```[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method unmute on channel flutter_midi)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      FlutterMidi.unmute (package:flutter_midi/flutter_midi.dart:47:42)
#3      MotivateViewModel.load (package:motivate/core/viewmodels/motivate_vm.dart:60:17)
#4      MotivateViewModel.loadData (package:motivate/core/viewmodels/motivate_vm.dart:42:5)
#5      _HomeState.afterFirstLayout (package:motivate/views/home.dart:31:14)
#6      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1064:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
#10     _rootRun (dart:async/zone.dart:1182:47)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method prepare_midi on channel flutter_midi)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      FlutterMidi.prepare (package:flutter_midi/flutter_midi.dart:23:24)
<asynchronous suspension>
#3      MotivateViewModel.load (package:motivate/core/viewmodels/motivate_vm.dart:62:17)
<asynchronous suspension>
#4      MotivateViewModel.loadData (package:motivate/core/viewmodels/motivate_vm.dart:42:5)
#5      _HomeState.afterFirstLayout (package:motivate/views/home.dart:31:14)
#6      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1064:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
#10     _rootRun (dart:async/zone.dart:1182:47)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by rodydavis** [comment]
There is no support for macos at this time.
